%%gen
    class ARCMStream {
        #std.vector~Entry~ entries
        #loadEntries() int8_t
        #skipBasicLoader() void
        #readHeader() bool
        #seekEntry(std.string filename) bool
        #seekEntry(uint16_t index) bool
        #readFile(uint8_t* buf, uint32_t size) uint32_t
        #writeFile(uint8_t* buf, uint32_t size) uint32_t
        #seekPath(std.string path) bool
        #Header header
        #Entry entry
        +ARCMStream(std.shared_ptr~MStream~ is)
    }
