%%gen
    class AttributeNameValue {
        -std.string _name
        -std.string _value
        +AttributeNameValue(std.string name, std.string value)
        +Name() std.string
        +Value() std.string
    }
