%%gen
    class BluetoothManager {
        -eBTBaudrate _mBTBaudrate
        -bool _mActive
        +isActive() bool
        +start() void
        +stop() void
        +toggleBaudrate() eBTBaudrate
        +service() void
    }
