%%gen
    class CRTMStream {
        #seekEntry(std.string filename) bool
        #seekEntry(uint16_t index) bool
        #readEntry(uint16_t index) bool
        #seekPath(std.string path) bool
        #readFile(uint8_t* buf, uint32_t size) uint32_t
        #writeFile(uint8_t* buf, uint32_t size) uint32_t
        +CRTMStream(std.shared_ptr~MStream~ is)
    }
