%%gen
    class fnTestTask {
        -int _count
        -int _i
        #start() int
        #pause() int
        #resume() int
        #abort() int
        #step() int
        +fnTestTask(int count)
        +fnTestTask() ~
        +get_progress() int
        +get_result() void *
    }
