%%gen
    class fnUDP {
        -int udp_server
        -in_addr_t multicast_ip
        -in_addr_t remote_ip
        -uint16_t server_port*
        -uint16_t remote_port*
        -char * tx_buffer
        -size_t tx_buffer_len*
        -cbuf * rx_buffer
        +fnUDP()
        +stop() void
        +begin(in_addr_t a, uint16_t p) bool
        +begin(uint16_t p) bool
        +beginMulticast(in_addr_t a, uint16_t p) bool
        +beginMulticastPacket() bool
        +beginPacket() bool
        +beginPacket(in_addr_t ip, uint16_t port) bool
        +beginPacket(const char *host, uint16_t port) bool
        +endPacket() bool
        +write(uint8_t) size_t
        +write(const uint8_t *buffer, size_t size) size_t
        +parsePacket() int
        +read() int
        +read(unsigned char* buffer, size_t len) int
        +read(char* buffer, size_t len) int
        +peek() int
        +available() int
        +flush() void
        +remoteIP() in_addr_t
        +remotePort() uint16_t
    }
