%%gen
    class FTPMFile {
        -openDir(std.string path) void
        -closeDir() void
        #bool dirOpened
        #std.shared_ptr~FTPMSession~ _session
        #getFS() FileSystemFTP*
        +std.string basepath
        +FTPMFile(std.string path)
        +getSourceStream(...) std.shared_ptr~MStream~
        +getDecodedStream(std.shared_ptr~MStream~ src) std.shared_ptr~MStream~
        +createStream(std.ios_base.openmode mode) std.shared_ptr~MStream~
        +isDirectory() bool
        +getLastWrite() time_t
        +getCreationTime() time_t
        +rewindDirectory() bool
        +getNextFileInDir() MFile*
        +mkDir() bool
        +exists() bool
        +remove() bool
        +rename(std.string dest) bool
        +readEntry(std.string filename) bool
    }
