%%gen
    class HTMLElement {
        +HTMLElement(void* internal)
        +HTMLElement(HTMLElement* element)
        +Attribute(const char* name) const char*
        +GetText() const char*
        +Query(const char* query) HTMLResult*
        +void* internal
    }
