%%gen
    class iecMeatloaf {
        -iecMeatloaf(uint8_t id) protected- public-
        -reset() void
        -executeData(const uint8_t *data, uint8_t dataLen) void
        -enable(std.string deviceids) void
        -disable(std.string deviceids) void
    }
