%%gen
    class IRCMFile {
        +IRCMFile()
        +IRCMFile(std.string path)
        +getSourceStream(...) std.shared_ptr~MStream~
        +getDecodedStream(std.shared_ptr~MStream~ src) std.shared_ptr~MStream~
        +createStream(std.ios_base.openmode mode) std.shared_ptr~MStream~
        +isDirectory() bool
    }
