%%gen
    class JiffyDOS {
        #uint8_t loadmode*
        #uint8_t skipeoi*
        #receiveByte(void) uint8_t
        #sendByte(uint8_t data, bool eoi) bool
        #sendByte(...) bool
        +JiffyDOS()
    }
