%%gen
    class LBRMFile {
        +LBRMFile(std.string path, bool is_dir)
        +getDecodedStream(std.shared_ptr~MStream~ is) std.shared_ptr~MStream~
        +rewindDirectory() bool
        +getNextFileInDir() MFile*
        +bool isDir
        +bool dirIsOpen
    }
