%%gen
    class MediaTypeIMG {
        -_sector_to_offset(uint16_t sectorNum) uint32_t
        +read(uint16_t sectornum, uint16_t *readcount) success_is_true
        +write(uint16_t sectornum, bool verify) success_is_true
        +format(uint16_t *responsesize) success_is_true
        +mount(...) mediatype_t
        +status(uint8_t statusbuff[4]) void
        +create(...) success_is_true$
    }
