%%gen
    class NetworkProtocolFS {
        #OpenMode
        #OpenMode openMode
        #std.string dir
        #std.string filename
        #std.string destFilename
        #int fileSize*
        #std.string dirBuffer
        #bool is_directory
        #uint16_t mode*
        #bool is_locked
        #open_file() bool
        #open_file_handle() bool*
        #open_dir() bool
        #open_dir_handle() bool*
        #mount(PeoplesUrlParser *url) bool*
        #umount() bool*
        #fserror_to_error() void*
        #resolve() void
        #update_dir_filename(PeoplesUrlParser *url) void
        #read_file(unsigned short len) bool
        #read_file_handle(uint8_t *buf, unsigned short len) bool*
        #read_dir(unsigned short len) bool
        #read_dir_entry(char *buf, unsigned short len) bool*
        #status_file(NetworkStatus *status) bool
        #status_dir(NetworkStatus *status) bool
        #close_file() bool
        #close_file_handle() bool*
        #close_dir() bool
        #close_dir_handle() bool*
        #write_file(unsigned short len) bool
        #write_file_handle(uint8_t *buf, unsigned short len) bool*
        #stat() bool*
        #rename(...) bool
        #del(...) bool
        #mkdir(...) bool
        #rmdir(...) bool
        #lock(...) bool
        #unlock(...) bool
        +bool rename_implemented
        +bool delete_implemented
        +bool mkdir_implemented
        +bool rmdir_implemented
        +NetworkProtocolFS(...)
        +NetworkProtocolFS() ~
        +open(...) bool
        +close() bool
        +read(unsigned short len) bool
        +write(unsigned short len) bool
        +status(NetworkStatus *status) bool
        +special_inquiry(uint8_t cmd) uint8_t
        +special_00(cmdFrame_t *cmdFrame) bool
        +special_40(...) bool
        +special_80(...) bool
        +perform_idempotent_80(...) bool
    }
