%%gen
    class NFSHandle {
        -std.shared_ptr~NFSMSession~ _session
        -int flags*
        +NFSHandle()
        +obtain(std.string localPath, int nfs_mode) void
        +dispose() void
    }
