%%gen
    class RS232ChannelProtocol {
        +getBaudrate() uint32_t*
        +setBaudrate(uint32_t baud) void*
        +getDTR() bool*
        +setDSR(bool state) void*
        +getRTS() bool*
        +setCTS(bool state) void*
        +setDCD(bool state) void*
        +getDCD() bool*
        +setRI(bool state) void*
        +getRI() bool*
    }
