%%gen
    class SerialClass {
        +printf(const char *fmt, ...) int
        +print(const char *s) void
        +print(const std.string s) void
        +println(const char *s) void
        +println(const std.string s) void
        +println() void
    }
