%%gen
    class SQLiteMStream {
        -std.string hash
        -generate(std.string data) uint32_t
        +SQLiteMStream(std.string path, std.ios_base.openmode m)
        +isOpen() bool
        +open(std.ios_base.openmode mode) bool
        +close() void
        +read(uint8_t* buf, uint32_t size) uint32_t
        +write(const uint8_t *buf, uint32_t size) uint32_t
        +seek(uint32_t pos) bool
    }
