    class tapclean_prg_t {
        <<struct>>
        +int type
        +const char* type_name
        +int is_cbm_header
        +int is_cbm_data
        +int start_addr, end_addr, size
        +const char* name
        +const uint8_t* data
        +int read_errors
        +int tap_start, tap_end
    }
