    class tapclean_scanners {
        <<91 scanner modules>>
        +turbotape_search() describe()
        +turbotape_fast_search() describe() Meatloaf addition
        +cyberload_f1..f4, visiload, usgold, novaload
        +freeload, pavloda, ocean, bleep, snakeload, more
    }
