%%gen
    class TCPMStream {
        #std.shared_ptr~TCPMSession~ _session
        +isNetwork() bool
        +TCPMStream(std.string path)
        +size() uint32_t
        +available() uint32_t
        +position() uint32_t
        +error() size_t
        +seek(uint32_t pos) bool
        +close() void
        +open(std.ios_base.openmode mode) bool
        +read(uint8_t* buf, uint32_t size) uint32_t
        +write(const uint8_t *buf, uint32_t size) uint32_t
        +isOpen() bool
    }
