%%gen
    class TCPMSession {
        -MeatSocket _socket
        +TCPMSession(std.string host, uint16_t port)
        +getScheme() std.string$
        +connect() bool
        +disconnect() void
        +keep_alive() bool
        +socket() MeatSocket*
    }
