    class wwwModules {
        <<free functions>>
        +proxy_handler() / proxy_register()
        +ws_handler() / ws_send_all() / ws_register()
        +webdav_handler() / webdav_register()
        +send_file() / send_file_parsed()
    }
