%%gen
    class XMLCopyAndReplace {
        -substitute(const std.string val) std.pair ~bool, std.string~
        -const std.unordered_map~std.string, std.string~ _params
        -const char _openDelim
        -const char _closeDelim
        +XMLCopyAndReplace(...)
        +VisitEnter(...) bool
        +Visit(const XMLText txt) bool
    }
